<?php
/**
 * Ebrook
 *
 * @category    Ebrook
 * @package     AnyPlaceMedia_SendSMS
 * @copyright   Copyright © 2021 Ebrook co., ltd. (https://www.ebrook.com.tw)
 * @source https://github.com/sendSMS-RO/sendsms-magento2.4
 */
?>
<p><?= $block->escapeHtml(__('To use this module, please enter your sendSMS login credentials inside the configuration page.'))?></p><br />
<p><?= $block->escapeHtml(__('You don\'t have a sendSMS account?'))?><br />
    <?= __('Register FREE <a href="http://www.sendsms.ro/en" target="_blank">here</a>.')?><br />
    <?= __('For more details, contact us <a href="https://www.sendsms.ro/en/contact-2/">here</a>.')?></p>
<p><?= $block->escapeHtml(__('In the settings page, under credentials, you will find a field for every order status avaible in Magento.'))?></p>
<p><?= $block->escapeHtml(__('You will need to enter a message to send an SMS for the order status.'))?></p>
<p><?= $block->escapeHtml(__('You can enter variables which will be filled based on the order informations.'))?></p>
<p><?= __('Example: <strong>Good day {billing_first_name}. Your order with the {order_number} is completed.</strong>')?></p>
