<?php
/**
 * Ebrook
 *
 * @category    Ebrook
 * @package     AnyPlaceMedia_SendSMS
 * @copyright   Copyright © 2021 Ebrook co., ltd. (https://www.ebrook.com.tw)
 * @source https://github.com/sendSMS-RO/sendsms-magento2.4
 */
?>

<form class="form" method="post"
    action="<?= $block->escapeHtml($block->getUrl(
        '*/*/*',
        ['_current' => true, '_use_rewrite' => true]
    )) ?>">
    <?= $block->getBlockHtml('formkey')?>
    <div class="fieldset-wrapper">
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field">
                    <label for="phone" class="admin__field-label">
                        <span><?= __('Phone')?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="text" id="phone" name="phone"
                        class="admin__control-text" required>
                    </div>
                </div>
                <div class="admin__field">
                    <label for="gdpr" class="admin__field-label">
                        <span><?= __('Add unsubscribe link?')?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="checkbox" id="gdpr" name="gdpr"
                        class="admin__control-checkbox-inline">
                    </div>
                </div>
                <div class="admin__field">
                    <label for="short" class="admin__field-label">
                        <span><?= __('Minimize urls?')?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="checkbox" id="short" name="short"
                        class="admin__control-checkbox-inline">
                    </div>
                </div>
                <div class="admin__field">
                    <label for="message" class="admin__field-label">
                        <span><?= __('Message')?></span>
                    </label>
                    <div class="admin__field-control">
                        <textarea id="message" name="message"
                            class="admin__control-textarea sendsms-char-count"
                            required></textarea>
                    </div>
                </div>
                <div class="admin__field">
                    <label class="admin__field-label"></label>
                    <div class="admin__field-control">
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action submit primary"
                                    title="Send Message">
                                    <span><?= __('Send Message')?></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</form>